spring.application.name=ms-guias-despacho

# Base de datos H2
spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

spring.jpa.hibernate.ddl-auto=update

# Consola H2
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# Azure AD B2C 
spring.security.oauth2.resourceserver.jwt.issuer-uri=https://login.microsoftonline.com/3d585b08-13da-4841-8fc7-6aaa89628e27/v2.0

spring.security.oauth2.resourceserver.jwt.jwk-set-uri=https://login.microsoftonline.com/3d585b08-13da-4841-8fc7-6aaa89628e27/discovery/v2.0/keys

# Logs
logging.level.org.springframework.security=DEBUG
logging.level.org.springframework.web=DEBUG
