spring.application.name=ms-guias-despacho

spring.datasource.url=jdbc:oracle:thin:@dsy2206_tp
spring.datasource.username=GRUPO9
spring.datasource.password=Password4827!
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.OracleDialect
