name: Deploy Spring Boot to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout código
        uses: actions/checkout@v4

      - name: Configurar Java 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Verificar secreto SSH
        run: |
          if [ -z "${{ secrets.EC2_SSH_KEY }}" ]; then
            echo "La llave está vacía"
            exit 1
          else
            echo "La llave fue recibida correctamente"
          fi

      - name: Dar permisos Maven
        run: chmod +x mvnw

      - name: Compilar proyecto
        run: ./mvnw clean package -DskipTests

      - name: Copiar JAR a EC2
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ec2-user
          key: ${{ secrets.EC2_SSH_KEY }}
          source: "target/ms-guias-despacho-0.0.1-SNAPSHOT.jar"
          target: "/home/ec2-user/"

      - name: Deploy aplicación
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ec2-user
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            killall java || true
            export TNS_ADMIN=/home/ec2-user/Wallet_DSY2206
            cd /home/ec2-user
            nohup java -jar target/ms-guias-despacho-0.0.1-SNAPSHOT.jar > app.log 2>&1 &
            sleep 10
            cat app.log
